spring:
  datasource:
    url: jdbc:h2:file:C:\Users\Ferg\Documents\demo
    driverClassName: org.h2.Driver
    username: sa
    password: password
jpa:
  database-platform: org.hibernate.dialect.H2Dialect
logging:
  level:
    org:
      springframework:
        cache: TRACE